### ISSUE TITLE
Example Request

### ISSUE THREAD

**Issue by will-hanson-pub** [getstation/electron-intercom-messenger#3]
Hey dude,

Can you add an example for how we can do an embedded intercom (instead of a new window) with a logged in user?

**Comment by alexstrat** [comment]
In the example, there is actually an [example with a `webview`](https://github.com/getstation/electron-intercom-messenger/blob/master/example/app.html#L16) that is commented. Give it a try, that's how we use it in production.

Regarding logged-in user, you need to do this on the main side:
```js
import * as electronIntercomMessenger from 'electron-intercom-messenger';

const messenger = electronIntercomMessenger.start(intercomSettings, widgetOptions);

messenger.update({/* user data */})
// will call https://developers.intercom.com/docs/intercom-javascript#section-intercomupdate
```
